apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    metadata:
      name: migrate
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: dmleobit/kubes_app:latest
        command: ['rails']
        args: ["db:migrate"]
        env:
          - name: DB_USERNAME
            value: postgres
          - name: DB_HOST
            value: postgres-cluster-ip-service
          - name: DB_DATABASE
            value: kubes_app
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pgpassword
                key: PGPASSWORD
