apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: sidekiq
  template:
    metadata:
      labels:
        component: sidekiq
    spec:
      containers:
        - name: sidekiq
          image: dmleobit/kubes_app:latest
          command: ["bundle"]
          args:
            - "exec"
            - "sidekiq"
          env:
            - name: DB_USERNAME
              value: postgres
            - name: DB_HOST
              value: postgres-cluster-ip-service
            - name: DB_DATABASE
              value: kubes_app
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
