default: &default
  adapter: <%= ENV.fetch('DB_ADAPTER', 'postgresql') %>
  pool: <%= ENV.fetch('DB_POOL', 5) %>

local: &local
  <<: *default
  encoding: <%= ENV.fetch('DB_ENCODING', 'unicode') %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  username: <%= ENV.fetch('DB_USERNAME', 'dmytromolodko') %>
  password: <%= ENV.fetch('DB_PASSWORD', '') %>
  port: <%= ENV.fetch('DB_PORT', 5432) %>

development:
  <<: *local
  database: <%= ENV.fetch('DB_DATABASE', 'kubes_dev') %>

test:
  <<: *local
  database: <%= ENV.fetch('DB_DATABASE', 'kubes_test') %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
